.TH DNF-AUTOCLEAN 1 "September 2025" "v1.0.0" "User Commands"
.SH NAME
dnf-autoclean \- clean old kernels and orphan packages on Fedora
.SH SYNOPSIS
.B dnf-autoclean
.SH DESCRIPTION
.B DNF AutoClean
is a simple tool that automatically removes old kernels,
orphan packages, and runs dnf autoremove. It includes a GUI frontend
and can be scheduled with systemd timers.

