name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate scripts
        run: |
          python3 -m py_compile dnf-autoclean.py dnf-autoclean-gui.py
      - name: Build tarball
        run: |
          tar -czf dnf-autoclean-1.0.0.tar.gz *
